### ISSUE TITLE
Readout "Battery" failed with message: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by thatwolfrio** [Macchina-CLI/libmacchina#136]
Not really sure what to do with this, as I don't know what file it's looking for when it gets this error or really anything going on. I'm also not sure what logs or anything to put along with this post, as I don't do this very often nor do I know if and/or where macchina outputs its logs or what logs would be relevant.

**Comment by thatwolfrio** [comment]
macchina doctor outputs this:
`Let's check your system for errors... Here's a summary:

We've collected 18 readouts, including 3 failed read(s) and 0 read(s) which resulted in a warning.
Readout "OperatingSystem" failed with message: This metric is not available on this platform or is not yet implemented by libmacchina.
Readout "WindowManager" failed with message: Unknown window manager.
Readout "Battery" failed with message: No such file or directory (os error 2)
`

**Comment by thatwolfrio** [comment]
I am using Linux, and sure. /sys/class/power_supply contains folders AC0 and BAT0
BAT0 contains 
alarm           charge_control_end_threshold  energy_full         hwmon2/       power/     serial_number  technology  voltage_min_design
capacity        cycle_count                   energy_full_design  manufacturer  power_now  status         type        voltage_now
capacity_level  device@                       energy_now          model_name    present    subsystem@     uevent

and AC0 contains
device@  hwmon0/  online  power/  subsystem@  type  uevent  wakeup35/

**Comment by thatwolfrio** [comment]
It's probably my own mistake, but nothing seems different when I run the command. It's just the same output as usual.

**Comment by thatwolfrio** [comment]
Weird, well is there anything else I could send to figure this out?

**Comment by thatwolfrio** [comment]
Well that's what's odd, is everything else works fine. Aside from the battery readout and the 2 others that -d pointed out, everything works. It's just those 3.

**Comment by thatwolfrio** [comment]
The OS makes sense, and the Window Manager also makes sense since I use KDE Plasma and it's window manager KWin. Just not really sure why the battery part isn't working. Maybe something is missing in the macchina install? I installed it from cargo, so I'm not really sure why it would be missing anything, but maybe that's it?

**Comment by thatwolfrio** [comment]
Yeah I assumed so. I have no idea what else would cause this though. Like you said, everything is there and looks fine so there's no clear reason as to why this is happening.

**Comment by FantasyTeddy** [comment]
I may have a theory to what is happening here:

In `macchina` only the `percentage()` and `status()` method of `BatteryReadout` are used, so we can rule out that the problem originates within the `health()` method.

- `percentage()`:
Lists all entries of `/sys/class/power_supply` and filters for anything starting with `BAT`. Inside this directory, we query the `capacity` file, which should be present according to @thatwolfrio's directory listing.
- `status()`:
Filters the `/sys/class/power_supply` directory for anything that does **not** start with `ADP` and then takes the **first** entry it finds.
⚠ What if this *first* entry is the `AC0` directory which does not contain the expected `status` file?

@grtcdr: Let me know what you think.
