### ISSUE TITLE
Support for `ndb` (and `bdb`) RPM backend(s)

### ISSUE THREAD

**Issue by Gobidev** [Macchina-CLI/libmacchina#154]
The current implementation of RPM package count only supports sqlite databases. This works on Fedora and similar distributions but RPM also supports the database formats `bdb` (based on Berkley DB) and `ndb` (RPM native implementation, used on OpenSUSE Tumbleweed) ([source](https://rpm.org/user_doc/db_recovery.html)).

This will probably be really hard to implement as I couldn't find any libraries to process RPM bdb databases, so this might require its own crate. The bdb part however might be less complicated, but is also less relevant, as I don't know any distributions that still use that backend.

This would not only add support for more distributions (like OpenSUSE) but also ensure ongoing support for currently supported distributions (like Fedora) that might switch to ndb in the future.

**Comment by CarterLi** [comment]
You may use librpm

Demo: https://github.com/LinusDierheimer/fastfetch/blob/dev/src/detection/packages/packages_linux.c#L230-L264
