### ISSUE TITLE
OperatingSystem implementation for Linux

### ISSUE THREAD

**Issue by be4zad** [Macchina-CLI/libmacchina#167]
It seems operating system name is same with distro name in hostnamectl.
Isn't it better to remove Distro and replace it by OperatingSystem?

**Comment by be4zad** [comment]
Oops, wrong repo

**Comment by be4zad** [comment]
Oops, wrong repo

**Comment by be4zad** [comment]
Oops, wrong repo

**Comment by be4zad** [comment]
```
behzad@arch ~> hostnamectl
Operating System: Arch Linux 
…
```

**Comment by grtcdr** [comment]
I made that distinction in the API to accommodate the differences in semantics between operating systems. Operating systems built on Linux refer to themselves as distributions and the API reflects that, whether that was the right choice is debatable. I just don't think it's worth breaking backwards-compatibility for such a minor problem.
