### ISSUE TITLE
Typo with Readouts.network type in docs?

### ISSUE THREAD

**Issue by justin13888** [Macchina-CLI/libmacchina#168]
Shouldn't the highlighted be [NetworkReadout](https://docs.rs/libmacchina/7.2.2/libmacchina/type.NetworkReadout.html)?

![image](https://github.com/Macchina-CLI/libmacchina/assets/20733699/14b20659-2c45-4a5d-9c3a-f72628aa7523)

Page referred: <https://docs.rs/libmacchina/7.2.2/libmacchina/struct.Readouts.html>

**Comment by grtcdr** [comment]
Yes, thanks for catching that.

I'll fix that right away.
