### ISSUE TITLE
Add a public IP address readout.

### ISSUE THREAD

**Issue by ngirard** [Macchina-CLI/libmacchina#26]
Displaying the global IP address would be useful.

I'd suggest taking a look at http://ifconfig.co

**Comment by grtcdr** [comment]
Hey @ngirard 

This feature is most likely not going to be added anytime soon, here's why:

- Using popular http libraries means we'll be importing well over 100 crates for one small features.
- More dependencies means longer build time.
- It's going to slow down the program dramatically, even though it would've been disabled by default. Still, Macchina's main goal is to display system information faster than one can blink their eye.

**Comment by ngirard** [comment]
Hey @grtcdr , thanks for the heads up!

Alright, maybe that's for the best: I'd have felt uncomfortable making an http request with each interactive shell instance, so I'd have switchd off the feature ; which defeats the purpose.

While it's all still fresh in your head, I'm curious to know, which crates are the best equivalent of curl / wget, on your opinion ?

**Comment by grtcdr** [comment]
> Alright, maybe that's for the best: I'd have felt uncomfortable making an http request with each interactive shell instance, so I'd have switched off the feature ; which defeats the purpose.

Yeah, I wouldn't either, most of these websites are HTTP only, and you may be exposing your IP address (and other stuff?) by making (constant) requests.

> While it's all still fresh in your head, I'm curious to know, which crates are the best equivalent of curl / wget, in your opinion ?

There's a very mature library that a lot of popular tools use, it's called [reqwest](https://github.com/seanmonstar/reqwest)

**Comment by ngirard** [comment]
Aha, nice ! Thanks for your feedback.

Feel free to close this issue anytime.

**Comment by grtcdr** [comment]
Thank you, have a good one :)
