### ISSUE TITLE
No packages reported on Ubuntu 20.04

### ISSUE THREAD

**Issue by ngirard** [Macchina-CLI/libmacchina#27]
Using latest precompiled binary on Ubuntu 20.04.1.

`macchina --no-ascii --no-box -X Packages` reports
```sh
Packages  —  0 (dpkg), 0 (flatpak), 0 (snap)
```

**Comment by grtcdr** [comment]
Hey,
So installing Lubuntu on a VM just didn't want to work, black screen and recovery mode didn't help whatsoever. I'm resorting to Linux Mint this time.

If I can replicate this issue, which hopefully I can, then a fix will roll out very soon.

**Comment by ngirard** [comment]
Good luck then, and let me know if I can help.

**Comment by grtcdr** [comment]
> Good luck then, and let me know if I can help.

Sure, thanks!

**Comment by grtcdr** [comment]
I get a black screen as soon as I sign in to Linux Mint too, this is unfair :(

**Comment by ngirard** [comment]
Sorry about that.
I'd recommend trying vanilla Ubuntu, since the installers from derived distributions are of subpar quality.

**Comment by grtcdr** [comment]
Okay, I might as well ask you some questions that can help me debug the root cause of the issue.

What's the output of
1. `ls /var/lib/dpkg/info | wc -l`
2. `ls /var/lib/flatpak/app | wc -l`
3. `ls /var/lib/snapd/snaps | wc -l`

**Comment by ngirard** [comment]
There you go:
```sh
ls /var/lib/dpkg/info | wc -l
16856
```
```sh
LANG=C ls /var/lib/flatpak/app | wc -l
ls: cannot access '/var/lib/flatpak/app': No such file or directory
```
(God forbid...)

```sh
ls /var/lib/snapd/snaps | wc -l
14
```

**Comment by grtcdr** [comment]
This helps a lot!

Thanks :)

**Comment by grtcdr** [comment]
Package count in the latest revision should no longer return 0 for any package manager.

And I just found out why it's displaying 0 packages.

Let's take a close look at how dpkg packages **were being** obtained:
1. libmacchina's dpkg implementation iterates through the entries of `/var/lib/dpkg/info`
2. It filters out any entry that doesn't end with ".list"
3. It returns the count of the filtered iterator

This fails because of _2_, because the function that determines whether a path, e.g. "/var/lib/dpkg/info/xorg-server.list" ends with a pattern, must be supplied the last component, not the extension.

So all in all, "/var/lib/dpkg/info/xorg-server.list" doesn't with ".list" but rather "xorg-server.list"

I'll fix this ASAP, thanks for being patient with me :smiley:

**Comment by ngirard** [comment]
No problem!

**Comment by grtcdr** [comment]
> No problem!

Should be fixed now :)

If you'd like to help me out a little more, then you might want to do the following:
1. Clone Macchina,
2. `macchina/Cargo.toml`: Bump the libmacchina dependency (and build dependency) to 0.2.7
3. Give it a spin to confirm that it has in fact been fixed.

**Comment by grtcdr** [comment]
So this isn't actually fixed at the moment, but I've applied a patch as pointed out by @uttarayan21
So you should be seeing correct package count in the next release.

**Comment by ngirard** [comment]
Will do, thanks

**Comment by grtcdr** [comment]
> If you'd like to help me out a little more, then you might want to do the following:
> 
>     1. Clone Macchina,
> 
>     2. `macchina/Cargo.toml`: Bump the libmacchina dependency (and build dependency) to 0.2.7
> 
>     3. Give it a spin to confirm that it has in fact been fixed.

So it's the same steps but it's version **0.2.8** rather than **0.2.7**.

**Comment by ngirard** [comment]
Working like a charm:
```
Packages  —  4897 (dpkg), 24 (cargo), 13 (snap)
```

Nice job !

**Comment by ngirard** [comment]
(I had a better feeling with 0 snap packages reported, tho)

**Comment by grtcdr** [comment]
> (I had a better feeling with 0 snap packages reported, tho)

Hahahahahahahahaha, nice one :laughing:

**Comment by grtcdr** [comment]
> ```
> Packages  —  4897 (dpkg), 24 (cargo), 13 (snap)
> ```

You're very lucky, macchina for me just refuses to print the package count for multiple package managers.

**Comment by ngirard** [comment]
Sorry about that !

**Comment by grtcdr** [comment]
> Sorry about that !

I wish I had a clue as to why this is happening on my machine and not on others.
