### ISSUE TITLE
Introduce a new readout: disk usage

### ISSUE THREAD

**Issue by grtcdr** [Macchina-CLI/libmacchina#32]
# How we can query

- Linux provides a ready to use struct, [stavfs64](https://docs.rs/libc/0.2.94/libc/struct.statvfs64.html), from which we can obtain disk usage.

- macOS's struct for querying disk usage is [statvfs](https://docs.rs/libc/0.2.94/x86_64-apple-darwin/libc/struct.statvfs.html)

- NetBSD [has one](https://rust-lang.github.io/libc/x86_64-unknown-netbsd/doc/libc/struct.statvfs.html) too, of course.

- Windows? I don't know, to be honest, but it's somewhere in [here](https://rust-lang.github.io/libc/x86_64-pc-windows-msvc/doc/libc/index.html)

**Comment by eoli3n** [comment]
I'm here :hand: (just to subscribe with a little word)

**Comment by grtcdr** [comment]
Great, we'll see how this evolves, usually features are implemented on Linux first, then they go through some testing and eventually they land for every platform.

**Comment by eoli3n** [comment]
I'll package your tool for Voidlinux, and I will test your feature on it. (if ZFS will be supported ?)

**Comment by grtcdr** [comment]
> I'll package your tool for Voidlinux, and I will test that feature on it. (if ZFS will be supported ?)

Well we don't have disk usage statistics yet :/

Thanks for making a request to package Macchina for Void :)

**Comment by eoli3n** [comment]
Obviously when it will be done :dancers:

**Comment by grtcdr** [comment]
Macchina was [rejected from void's repository](https://github.com/void-linux/void-packages/pull/31361) a little while ago, so they'll most likely reject your PR too.

**Comment by eoli3n** [comment]
Don't get frustrated about the bad communication.
I like your project, and will package it for Voidlinux when it will sufficiently differ from neofecth :)

**Comment by grtcdr** [comment]
> Don't get frustrated about the bad communication.

It's okay, things of this nature happen sometimes but I didn't expect it to escalate to the point that it did.

> I like your project, and will package it for Voidlinux when it will sufficiently differ from neofetch :)

Thank you :smile:

**Comment by grtcdr** [comment]
@eoli3n Disk support [is here](https://github.com/Macchina-CLI/libmacchina/pull/58), but it's not as customizable as I'd like it to be. As soon as we complement it with some extensibility, it'll be included as a readout in _macchina_.
