### ISSUE TITLE
Android readouts fail on SELinux Enforcing

### ISSUE THREAD

**Issue by uttarayan21** [Macchina-CLI/libmacchina#33]
So I just switched to LineageOS 18.1 and few of android readouts are failing since it has SELinux enforced.

Kernel can still be accessed using `uname -a`.

Also it seems that `/proc/loadavg` is populated with values now however only adb shell can access it, but I haven't tested the libc::getloadavg yet. Uptime can also be parsed so its possible to read CPU usage.

Battery can still be accessed in termux though.

Currently `host` and `kernel` readouts fail in both termux and in adb shell.

![android](https://user-images.githubusercontent.com/18732700/116828625-7bda3a00-abbd-11eb-8e62-3c2171a3fb92.png)
`LocalIP` readout has failed in this case since WiFi was turned off.

**Comment by grtcdr** [comment]
Android uses SELinux too, any reason why the Android implementation doesn't work for LineageOS?

**Comment by uttarayan21** [comment]
My last rom was Pixel Experience and on my build it didn't Enforce SELinux. In that rom the SELinux is set to Permissive so the macchina build worked fine there.

I haven't tried any of this in a stock rom though.

**Comment by grtcdr** [comment]
> My last rom was Pixel Experience and on my build it didn't Enforce SELinux. In that rom the SELinux is set to Permissive so the macchina build worked fine there.
> 
> I haven't tried any of this in a stock rom though.

Oh thanks for the clarification!

It seems like we might need a new implementation that targets Android other Android-based operating systems that have SELinux enabled.

**Comment by uttarayan21** [comment]
I'd say most of the stuff is already there just maybe add a fallback to parse some command outputs like 
`uname -sr` or `hostname` both of which give correct outputs.

**Comment by grtcdr** [comment]
> I'd say most of the stuff is already there just maybe add a fallback to parse some command outputs like
> `uname -sr` or `hostname` both of which give correct outputs.

We'll have to explore our options by experimenting, calling commands is always costly.

**Comment by grtcdr** [comment]
During the build phase, we should check if SELinux is enabled, and have a feature which depending on the enforcement of SELinux, calls the appropriate functions for system fetching.

**Comment by uttarayan21** [comment]
> During the build phase, we should check if SELinux is enabled...

I don't think anyone is going to build for android on android it self ( takes like 10 minutes to build ), most likely they are going to cross compile. So checking SELinux will only tell about the host's status.

Also we are building with min api level 21 which is from when SELinux was enforced, so someone is less likely to run a permissive build.

**Comment by grtcdr** [comment]
> > During the build phase, we should check if SELinux is enabled...
> 
> I don't think anyone is going to build for android on android it self ( takes like 10 minutes to build ), most likely they are going to cross compile. So checking SELinux will only tell about the host's status.
> 
> Also we are building with min api level 21 which is from when SELinux was enforced, so someone is less likely to run a permissive build.

So what do you suggest that we do?

**Comment by uttarayan21** [comment]
I think I saw something like a `gethostname` function.
I'll try to make that work.
As for the kernel I haven't looked into it yet.

On 03/05/21 09:57PM, Taha Aziz Ben Ali wrote:
>         During the build phase, we should check if SELinux is enabled...
> 
>     I don't think anyone is going to build for android on android it self (
>     takes like 10 minutes to build ), most likely they are going to cross
>     compile. So checking SELinux will only tell about the host's status.
> 
>     Also we are building with min api level 21 which is from when SELinux was
>     enforced, so someone is less likely to run a permissive build.
> 
> So what do you suggest that we do?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.*
> 

-- 
Uttarayan Mondal

**Comment by uttarayan21** [comment]
Okay so I got the `libc::getshotname` function to work. I will also try to make `libc::uname` to work.   
As for the `Ctl` and `Sysctl`, I don't think we need them on android, since they don't work on SELinux Enforced anyways and the previous function seem to work on both Enforced and Permissive mode.

**Comment by grtcdr** [comment]
Sounds great!

**Comment by uttarayan21** [comment]
Fixed now.  
Will open a pull request after I clean up the code.

![macchina](https://user-images.githubusercontent.com/18732700/117333727-d70a7600-aeb6-11eb-96d4-3c468d288f73.png)

**Comment by uttarayan21** [comment]
Fixed in #37
