### ISSUE TITLE
[BUG] Terminal info incorrect after invoking a new shell with "bash"

### ISSUE THREAD

**Issue by alex67x** [Macchina-CLI/libmacchina#38]
**Describe the bug**
If a new bash shell is invoked from the terminal then the "Terminal" information from macchina changes from the terminal name to the shell name.

**To Reproduce**
1. Open terminal
2. Execute macchina
3. Note that the "Terminal" information from macchina is correct ("Terminal  —  alacritty")
4. From the opened terminal invoke a new shell with "bash" 
5. Execute macchina
6. Now in the "Terminal" info is displayed the shell name ("Terminal  —  bash")

**Expected behavior**
The terminal information should remain "alacritty"

Note that if I invoke a new bash shell with "exec bash" instead of "bash" the issue does not occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/4000159/118404095-2486a000-b67a-11eb-8323-bda828009497.png)

**`macchina --doctor` output**
Let's check your system for errors... Here's a summary:

We've collected 16 readouts, including 1 failed read(s) and 1 read(s) which resulted in a warning.
Readout "Battery" failed with message: No such file or directory (os error 2)

1 of the 2 unsuccessful read(s) resulted in a warning:
Readout "OperatingSystem" threw a warning with message: This metric is not available on this platform or is not yet implemented by Macchina.

**System Information**
 - Distribution: ArcoLinux
 - Desktop Environment: Qtile 0.17.0
 - Operating System: Arch Linux
 - Kernel: 5.10.36-1-lts  
 - Terminal: alacritty 0.7.2
 - Macchina's version: 0.7.4
 - Bash version: version 5.1.8(1)-release

**Comment by grtcdr** [comment]
The current implementation is pretty limited, the only reasonable solution is using the display server (X and Wayland) to retrieve this kind of information, instead of hardcore-parkouring through `/proc`, X can gather this info easily and reliably. 

I'll look be looking into this in the coming days.

**Comment by grtcdr** [comment]
This issue is resolved by 0d03ac, you can build `macchina` from source if you'd like to skip waiting on a new release.

**Comment by 0323pin** [comment]
@grtcdr not to disturb your priorities and feeling bad to post on a closed issue but, ...

The solution doesn't apply here.
Having `ksh` as shell, launch `xterm` and from there launch `nu`, then `macchina` reports the following,

SHELL: ksh
TERMINAL: ksh

Thoughts?

**Comment by grtcdr** [comment]
I'm pretty sure the fix was never applied for NetBSD, I'll get it fixed ;)

**Comment by grtcdr** [comment]
@0323pin #66 has been merged

**Comment by 0323pin** [comment]
@grtcdr Thanks! Really appreciated.
Anything else NetBSD is lagging behind now?
Except for the thing with screen resolution.

**Comment by grtcdr** [comment]
Performance is the only thing that stands out, to be honest. We're making calls to sysctl, which is slower than using `sysinfo`, and battery fetching is done through commands, too.

**Comment by 0323pin** [comment]
> Performance is the only thing that stands out

Guess we need to live with that for now.
`sysinfo` has shitty support for NetBSD. Basically, they have only implemented the bare minimum to allow the crate to compile as a dependency of other crates.

**Comment by 0323pin** [comment]
@grtcdr anyway, still lightning fast when compared to `neofetch` :)

**Comment by grtcdr** [comment]
> still lightning fast

I guess... But I'm still not satisfied, 5ms execution time has spoiled me...
