### ISSUE TITLE
Possible bug in machine field ?

### ISSUE THREAD

**Issue by uttarayan21** [Macchina-CLI/libmacchina#48]
![Screenshot from 2021-06-23 20-06-54](https://user-images.githubusercontent.com/18732700/123116595-a9758e00-d45e-11eb-82e1-4bda8b4074e2.png)

My laptop broke so the discovery to this :)

**Comment by grtcdr** [comment]
Ah dang it!

That phrase should **not** show up... It should be replacing "To be filled by O.E.M." with an empty string whenever it finds it, but for some reason it's printing that instead. Can you check if the files that we're reading from aren't actually the cause so we can pinpoint where the issue is creeping up from?

**Comment by uttarayan21** [comment]
Here you go !
![Screenshot from 2021-06-23 20-41-12](https://user-images.githubusercontent.com/18732700/123122122-5eaa4500-d463-11eb-98a6-9a93ad8fa035.png)
I have no clue what is supposed to be in there but it seems that `.replace` probably isn't replacing multiple "To be filled by O.E.M" strings.

**Comment by grtcdr** [comment]
> I have no clue what is supposed to be in there but it seems that `.replace` probably isn't replacing multiple "To be filled by O.E.M" strings.

Yup, I'll :mag_right: investigate the issue.

**Comment by grtcdr** [comment]
Uhm, I'm not exactly sure why this is occuring, file processing looks good as far as I can tell... :confused:

**Comment by uttarayan21** [comment]
I'll try to debug this later since college is really hectic right now.

**Comment by grtcdr** [comment]
> I'll try to debug this later since college is really hectic right now.

I bet, it was really stressful these couple weeks for me too, good luck with everything :smile:

**Comment by grtcdr** [comment]
Found the culprit!

Right around the end of `linux::machine()` we have:

```rust
if family == name && family == version {
            return Ok(family);
        } else if version.is_empty() || version.len() <= 15 {
            return Ok(new_product.into_iter().join(" "));
        }

        Ok(version)
```

First condition & second condition are not satisfied, so it ends up returning version, which in your case is "To be filled..."

**Comment by grtcdr** [comment]
I hate the diversity of the information that manufacturers provide or don't provide in this case. We'll have to add a new set of conditions or somehow simplify it and make it a lot more maintainable for the future.
