### ISSUE TITLE
[BUG] Support CMB0 battery device

### ISSUE THREAD

**Issue by ynavott** [Macchina-CLI/libmacchina#50]
**Describe the bug**
On my LG Gram 15", the battery device is named `CMB0` and not `BAT0` like on most computers. As such, macchina is unable to read the battery status.

**To Reproduce**
1. Verify that the output of `ls /sys/class/power_supply` returns `CMB0` and not `BAT0`
2. Run macchina.
3. No battery information is displayed.

**Expected behavior**
Macchina should detect the battery device correctly.

**`macchina --doctor` output**
```
Let's check your system for errors... Here's a summary:

We've collected 17 readouts, including 1 failed read(s) and 2 read(s) which resulted in a warning.
Readout "Battery" failed with message: No such file or directory (os error 2)

2 of the 3 unsuccessful read(s) resulted in a warning:
Readout "OperatingSystem" threw a warning with message: This metric is not available on this platform or is not yet implemented by Macchina.
Readout "DesktopEnvironment" threw a warning with message: You appear to be only running a window manager.
```

**System Information**
You don't have to provide this information if you're not comfortable doing so, but it'll help us solve the issue a lot faster.
 - Distribution: Arch
 - Desktop Environment: Openbox WM
 - Operating System: Linux
 - Terminal: Kitty
 - Macchina's version: 0.9.2

**Comment by grtcdr** [comment]
Okay, patches are in!

If you'd like to help me test them out, you can clone macchina and switch to branch `path-50-lm` and build the project from there :)

**Comment by ynavott** [comment]
> No, I'll move it for you.
> 
> I'll be ignoring any directories containing `ADP` and reading stats from one of the other directories in the new implementation (until I add two battery support)

I am not sure this is a good idea - I think USB power delivery devices are also listed in that directory. Better to just add a search for both `CMB0` in addition to the search for `BAT0` and not just dumping whatever is in the directory except `ADP*`

**Comment by ynavott** [comment]
I guess that's also true. Sadly I am completely clueless in rust, otherwise
I would have just submitted the PR myself.

Regarding the patch - I still need to compile it and check. Had a busy day,
so will probably get around to it later today/tomorrow morning and report
my findings.

**Comment by grtcdr** [comment]
@ynavott Have you tested it out? I'd like to proceed by merging the new changes.

**Comment by grtcdr** [comment]
Already merged, closing...
