### ISSUE TITLE
[netbsd] libmacchina fails to build following `vergen` dependency addition

### ISSUE THREAD

**Issue by grtcdr** [Macchina-CLI/libmacchina#55]
```
====
   Compiling git2 v0.13.21
error[E0609]: no field `uid` on type `&Process`
   --> /usr/pkgsrc/wip/macchina/work/vendor/vergen-5.1.15/src/feature/si.rs:265:28
    |
265 |     *user.uid() == process.uid
    |                            ^^^ unknown field

error: aborting due to previous error

For more information about this error, try `rustc --explain E0609`.
error: could not compile `vergen`

To learn more, run the command again with --verbose.
*** Error code 101

Stop.
bmake[1]: stopped in /usr/pkgsrc/wip/macchina
*** Error code 1

Stop.
bmake: stopped in /usr/pkgsrc/wip/macchina
====
```

**Comment by grtcdr** [comment]
@uttarayan21 does vergen not work on NetBSD?

**Comment by uttarayan21** [comment]
I haven't actually tried to cross compile it for netbsd, So I don't know. I'll try to compile on my local machine tomorrow.

**Comment by grtcdr** [comment]
Me neither, and it's a little unfortunate that I removed NetBSD from our actions right before the feature was added.

**Comment by uttarayan21** [comment]
Haha that's true and theres no netbsd check for libmacchina in the first place.

**Comment by grtcdr** [comment]
Yeah...

**Comment by uttarayan21** [comment]
Seems to build fine on my machine on the latest commit as well as 0.8.1
![libmacchina](https://user-images.githubusercontent.com/18732700/130184405-8733b600-6322-458f-a43f-695c0f8fda22.png)

**Comment by grtcdr** [comment]
Can you try building macchina?

**Comment by uttarayan21** [comment]
Compiling macchina gives me a linker ( the x11 ) error but vergen seems to compile.
![Screenshot from 2021-08-20 17-51-46](https://user-images.githubusercontent.com/18732700/130232389-321a3be7-7915-4f2d-ad26-48bfc43f0009.png)

**Comment by grtcdr** [comment]
That's weird, pin can't seem to compile the program... I'll have a deeper look into this, as I'm also looking into completely removing X11 bindings as they don't seem to be working (linux is prefering /sys/class/drm for some reason) and I'm pretty sure NetBSD is using ACPIVGA rather than X11.

**Comment by grtcdr** [comment]
Brought back NetBSD for macchina's actions and it isn't failing; which begs the question: why is it failing on actual systems running NetBSD?

**Comment by uttarayan21** [comment]
Haha ! No clue as to why that is. I guess some rust library mismatch or something.

**Comment by grtcdr** [comment]
I'm building it as we speak in a VM

**Comment by grtcdr** [comment]
![image](https://user-images.githubusercontent.com/35816711/130263677-b04b5515-eb82-4ce1-a7ad-c92fed6cac89.png)

Same issue as reported, should we file this?

**Comment by uttarayan21** [comment]
Yeah probably should file this. Compiles when cross compiled but not when native lol.

**Comment by grtcdr** [comment]
> Compiles when cross compiled but not when native lol.

Yeah, confusing...

I filed an issue at vergen when it should have been in git2-rs

**Comment by grtcdr** [comment]
@uttarayan21

I have reason to believe that the error is only produced on versions of Rust **< 1.54.0**, as our runners are all on that version and they have no problem compiling the code.

pkgsrc, NetBSD's package manager, [packages Rust 1.52.0](https://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/lang/rust/index.html) at the time of writing this, so this could be a version incompatibility issue.

I'll keep you posted if it turns out to be something else.

**Comment by uttarayan21** [comment]
Ah I see.  I thought that could happen.

**Comment by grtcdr** [comment]
### I didn't lol, I was scrambling for ideas until pin asked about the version we were running

**Comment by 0323pin** [comment]
Rust-1.54.0
NetBSD-current

So, I've created a GitHub account in order to have easier communication.
I still can't compile any version of macchina after 0.9.2 because of the vergen crate. git2 is not an issue, it compiles just fine as a dependency of onefetch.

Here's the error,
---
error[E0609]: no field `uid` on type `&Process`
   --> /usr/pkgsrc/wip/macchina/work/vendor/vergen-5.1.15/src/feature/si.rs:265:28
    |
265 |     *user.uid() == process.uid
    |                            ^^^ unknown field

error: aborting due to previous error

For more information about this error, try `rustc --explain E0609`.
error: could not compile `vergen`

To learn more, run the command again with --verbose.
*** Error code 101

Stop.
---
I've tried building it with the following patch
`vergen = { version = "5.1.15", default-features = false, features = ["build","cargo","git","rustc"] }` but, it still fails. I wonder why it's trying to build si even after disableing the future.

**Comment by grtcdr** [comment]
Hey pin!

My guess is that we're making calls to vergen methods even if you try to disable the features, one way to get around this is to disable them for NetBSD, until vergen maintainers add support for the platform.

**Comment by 0323pin** [comment]
@grtcdr can we please do this? I'll post the message above on the vergen issue you've raised.

**Comment by grtcdr** [comment]
In `build.rs` (both macchina and libmacchina) we should set up a check so it doesn't export the commit version and fail at build time for NetBSD.

I'll do this when as soon as I can :)

**Comment by grtcdr** [comment]
I should've anticipated this; leaving early before any vergen code is executed does not resolve the issue (tested it in my VM), but I'll leave it there for now. Maybe I can come up up with something...

**Comment by 0323pin** [comment]
@grtcdr thank you for looking into this, I'll be patient :)

**Comment by 0323pin** [comment]
Building `vergen` as a standalone crate fails with the same error.
However, building it with the `si` feature disabled compleates successfuly.

```
===> Building for vergen-5.1.15
   Compiling libc v0.2.101
   Compiling autocfg v1.0.1
   Compiling proc-macro2 v1.0.29
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.76
   Compiling version_check v0.9.3
   Compiling pkg-config v0.3.19
   Compiling tinyvec_macros v0.1.0
   Compiling matches v0.1.9
   Compiling rustversion v1.0.5
   Compiling unicode-bidi v0.3.6
   Compiling semver v1.0.4
   Compiling log v0.4.14
   Compiling percent-encoding v2.1.0
   Compiling anyhow v1.0.44
   Compiling cfg-if v1.0.0
   Compiling bitflags v1.3.2
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling tinyvec v1.4.0
   Compiling form_urlencoded v1.0.1
   Compiling unicode-normalization v0.1.19
   Compiling jobserver v0.1.24
   Compiling time v0.1.44
   Compiling quote v1.0.9
   Compiling idna v0.2.3
   Compiling rustc_version v0.4.0
   Compiling cc v1.0.70
   Compiling url v2.2.2
   Compiling libz-sys v1.1.3
   Compiling libgit2-sys v0.12.23+1.2.0
   Compiling chrono v0.4.19
   Compiling thiserror-impl v1.0.29
   Compiling enum-iterator-derive v0.7.0
   Compiling vergen v5.1.15 (/usr/pkgsrc/wip/vergen/work/vergen-5.1.15)
   Compiling thiserror v1.0.29
   Compiling enum-iterator v0.7.0
   Compiling getset v0.1.1
   Compiling git2 v0.13.22
    Finished release [optimized] target(s) in 7m 55s
$ 
```

**Comment by grtcdr** [comment]
Good to hear that it's *somewhat* finally working, does macchina launch just fine?

**Comment by 0323pin** [comment]
@grtcdr This was building `vergen` standalone with the `si` feature off.
I can not build `macchina` itself even patching `Cargo.toml` to turn the feature off. Maybe you guys could try to make it possible to disable the `si` feature.

**Comment by grtcdr** [comment]
Is this what you're using?

```rust
[build-dependencies]
vergen = { version = "5.1.15", default-features = false, features = ["build","cargo","git","rustc"] }
`

**Comment by 0323pin** [comment]
@grtcdr I have an idea actually. I was using the above on `macchina` Cargo.toml, which doesn't help. This is probably bacause the feature is sill being called from `libmacchina` Cargo.toml.

Do you you want me to try to patch both Cargo.toml files and regenerate the Cargo-lock for both. I could try to build `macchina` then.

**Comment by grtcdr** [comment]
Yeah, please, go ahead :)

**Comment by 0323pin** [comment]
@grtcdr I can't seem to patch `libmacchina` Cargo.toml as the file is set to autoupdate when something changes. This causes the patch to be rejected as there are mismatches :(

**Comment by grtcdr** [comment]
I'm not sure what you mean, libmacchina is sourced through its latest version (from crates.io), how does your patch work?

**Comment by 0323pin** [comment]
This has to do with how patches are applied in pkgsrc.
One way to see if this works would be to use
`vergen = { version = "5.1.15", default-features = false, features = ["build","cargo","git","rustc"] }`
instead of
`vergen = "5.1.15"`

in both `macchina` and `libmacchina` Cargo.toml files.

**Comment by grtcdr** [comment]
Oh, so you'd like me to apply these specific changes?

**Comment by uttarayan21** [comment]
Still seems to build fine in a docker container for me though. (main branch / no changes ) 
![macchina](https://user-images.githubusercontent.com/18732700/133071780-977854ec-5420-4cd8-8ac5-9699130f2b6e.png)

**Comment by grtcdr** [comment]
Thing is, cross is giving a false positive; building it in a native/VM environment throws the expected errors.

**Comment by 0323pin** [comment]
@grtcdr Give me one more try, I'll try to fool the system ;)

@uttarayan21 The problem is `sysinfo` has basically no support for NetBSD. I guess the issues are only visible when compiling natively.

**Comment by uttarayan21** [comment]
Ah so that's the problem. I'm curious what happens with the resulting binary though.

**Comment by grtcdr** [comment]
> Ah so that's the problem. I'm curious what happens with the resulting binary though.

Me too, panic on `--version` maybe?

**Comment by 0323pin** [comment]
Ok, I'll try to explain why I can patch `macchina`'s Cargo.toml but not `libmacchina`'s one.
When patching inside pkgsrc with the systems patching tool a copy of the original file to be patches is copied to `file-name.orig` and the patch is represented by a new file `file-name` Then a `diff -u` is applied to generate the unified diff which is applied at build time.

For `macchina` inside the build directory you will then find `Cargo.toml` and `Cargo.toml.orig`. But, `libmacchina` is set to pull the dependencies from crates.io at build time, which means that inside the build directory there are already `Cargo.toml.orig`, the one in your repo and a `Cargo.toml`, which has the updated dependencies. This results in a `diff -u` operation between the two and a broken patch. Unfortunately the naming of the files is the same as use by pkgsrc and this causes the issue.

The only way I currently see to be able to test this is if you guys could apply the change suggested above, maybe in a seperate branch and provide an rc-release, test-release or alpha. I can then try the build and if it works you can merge, if not, we are simply looking in the wrong place.

`vergen` does build standalone if I disable the `si`-feature.

**Comment by grtcdr** [comment]
Okay, I see how the pieces are connected now.

I'll start working on an alpha release when I get home :)

**Comment by 0323pin** [comment]
@grtcdr Thanks! Perhaps revert your last two changes to see if it builds with only the `vergen` change compared to the latest release. Up to you really.

**Comment by uttarayan21** [comment]
> > Ah so that's the problem. I'm curious what happens with the resulting binary though.
> 
> Me too, panic on `--version` maybe?

@0323pin @grtcdr 

Since I was curious I made a netbsd kvm and tested the binary built from docker and It didn't panic and actually seems to work.
![Screenshot from 2021-09-13 19-19-07](https://user-images.githubusercontent.com/18732700/133095858-34770255-1b02-4e53-b31e-c5871d8f7415.png)

**Comment by grtcdr** [comment]
Whaaat... You gotta let us in on your secret.

**Comment by 0323pin** [comment]
@grtcdr He's running a docker-built binary and not a native built one.
@uttarayan21 Actually, it doesn't surprise me that much. Since, you are apparently not using the `sysinfo` bits, why should it panic?

I run `nushell` and it doesn't panic but any functionality that depends on `sysinfo` simply returns nothing.
This is why I believe that removing the `si`-feature from `vergen` on both `macchina` and `libmacchina` will solve the problem.

Anyway, good to know the docker binary is running without panic but, it does not help us shipping a natively built binary.

**Comment by uttarayan21** [comment]
That's true  running `--doctor` reveals that the kernel readout fails. I'm learning how to use netbsd a bit to test out some more and try out building it natively right now.

**Comment by grtcdr** [comment]
Kernel should fail on NetBSD, so no worries there.

**Comment by uttarayan21** [comment]
Yeah its a fresh install without x11 and with nothing but sshd and dhcp enabled. So thats why many stuff might not work.

**Comment by grtcdr** [comment]
Resolution doesn't require X11. After we started utilizing the ACPIVGA driver for NetBSD, and using `/sys/class/drm` for Linux, I decided to ditch X11.

**Comment by grtcdr** [comment]
I'll start working on the alpha branch/release.

**Comment by grtcdr** [comment]
Sorry for taking so long, the [alpha branch](https://github.com/Macchina-CLI/macchina/tree/1.1.4-alpha) is available now

**Comment by 0323pin** [comment]
Thanks! I'll try building from the alpha and let you know but, I don't think I'll have time today :(

**Comment by 0323pin** [comment]
@grtcdr and @uttarayan21 The good news first. It builds successfully from 1.0.4-alpha :)
![2021-09-14-105549_1120x632_scrot](https://user-images.githubusercontent.com/90570748/133230571-ad2954f9-8c15-479c-b080-20a25fa51663.png)

As you can see, it doesn't fetch resolution, though.
I have hidden LocalIP for the screenshot and usually I hide resolution as well but, I've left it as default for this screenshot.

**Comment by grtcdr** [comment]
You might be missing the ACPIVGA driver, since you reinstalled your whole system.

**Comment by 0323pin** [comment]
@grtcdr  

```
dmesg | grep vga
[1.03838] acpivga0: connected output devices:
[1.03838] acpivga0: (0x0400) (acpiout1): Unknown Output Device, head 0

```

Will you be able to merge the changes into the main branch within a week or so?
I would like us to branch the stable release with an updated version of `macchina`, even if it's without resolution.

**Comment by grtcdr** [comment]
Of course :) I'm back to uni, but I can set aside a couple hours to merge and release.

Why is it throwing an error on the driver side?

**Comment by 0323pin** [comment]
I have no clue and I hardly had time to build the alpha today but, I'm happy I did :)
The most important is that the package now builds.

We can look at the resolution again. I'd need you to point me to where in the code this is being defined.

Right now, I'm happy it builds.

**Comment by grtcdr** [comment]
I'm back home, and I'll be publishing v1.1.4 in the coming hours. I have a few things to test on the NetBSD side, but I won't be long.

**Comment by grtcdr** [comment]
> We can look at the resolution again. I'd need you to point me to where in the code this is being defined.

Sure thing, we're making a simple sysctl call, essentially getting the value of `hw.acpi.acpiout0.brightness` which the requires the presence of the ACPIVGA driver. My question is, does it come preinstalled into every NetBSD system?

https://github.com/Macchina-CLI/libmacchina/blob/6ddf669a6143168ee7c438e591f52e03cafa503f/src/netbsd/mod.rs#L129-L148

**Comment by grtcdr** [comment]
@0323pin As far as the release goes, we're all set.

About the failing readouts, can you open an issue once you're sure the resolution errors are not in fact stemming from libmacchina?

Theoretically speaking, if something were to go wrong, it'd most likely be the driver that's at fault (or a misconfiguration). All that libmacchina does is query the driver through sysctl.

**Comment by 0323pin** [comment]
@grtcdr thank you. Nice to "work" again with you.
@uttarayan21 thanks to you also for all the support.

I'll look into the resolution bit and will open a new issue if required. I need to get other things ready for the branching, namely a few other packages up-to-date, but I'll be back ;)

**Comment by grtcdr** [comment]
Always a pleasure, pin :)

**Comment by 0323pin** [comment]
>  we're making a simple sysctl call, essentially getting the value of hw.acpi.acpiout0.brightness which the requires the presence of the ACPIVGA driver.

Sorry about continuing the discussion here but, I'm still unsure this deserves a new issue.
```
$ sysctl hw.acpi.acpiout0.brightness 
hw.acpi.acpiout0.brightness = 100
```

So, no problem there. Yes, this is default functionality.

**Comment by grtcdr** [comment]
No worries.

If _sysctl_ is reporting it, and we're not picking up on it, then the only logical theory is that something must be going wrong, on the _libmacchina_ side. The only issue is, I haven't touched `netbsd::GeneralReadout::resolution()` since it was first implemented. Well, that's a lie, it did go through one change; the removal of calls to the Xorg libraries. Thing is, we haven't had any reports of it breaking after this (quite old) code cleanup.

**Comment by grtcdr** [comment]
Wait, why are we querying for brightness in `resolution()`, oh man :facepalm:

**Comment by 0323pin** [comment]
That's what I thought as well ;)

**Comment by grtcdr** [comment]
This went unnoticed for the entirety of its existence, which is roughly a couple of months.

I have a  plan though:

- Research. I need to find some way to query resolution, without relying on the windowing system. Is there a NetBSD equivalent to `/sys/class/drm`?
- Move the contents of resolution into `backlight()`, which for now, is in its own separate branch, waiting to be implemented for Windows, macOS and Android.
- Publish a new release, with resolution removed for NetBSD; Incorrect information contributes to confusion, and I hate being confused.

**Comment by 0323pin** [comment]
> This went unnoticed for the entirety of its existence, which is roughly a couple of months.

This is the same time span that my builds were failing and the package wasn't updated on NetBSD.

**Comment by grtcdr** [comment]
I'm still surprised at my level of inattentiveness. 

Anyways, I'm going to follow the plan and try and roll out a new release by the end of the day. I'll have to allocate a fair bit of time to do some proper research though, as using Xorg in any way just breaks CI, leaving us blind to potential bugs and breakages.

**Comment by 0323pin** [comment]
@grtcdr 
> Is there a NetBSD equivalent to /sys/class/drm?

Bare with me, I know which resolution I have on my screen so greping dmesg is tempting ;)

```
$ dmesg | grep 1366x768
[     4.890219] intelfb0: framebuffer at 0xc0097000, size 1366x768, depth 32, stride 5504
```

Now, you can already see the issue with this, right?
This only applies to intel gpu. I try asking someone if there's a general way.

**Comment by grtcdr** [comment]
Still, that's a really good start. I suspect there's a kernel interface which we can query to access resolution info, no matter which card it is.

**Comment by 0323pin** [comment]
@grtcdr Waiting for an answer, I'll let you know once I find out.
For now, I've merged 1.1.4, https://mail-index.netbsd.org/pkgsrc-changes/2021/09/15/msg240675.html

**Comment by 0323pin** [comment]
@grtcdr I've sent you a c-code file through e-mail earlier today. I will send you an upgraded version soon.

**Comment by grtcdr** [comment]
I'll check it out, thank you for the help :)
