### ISSUE TITLE
Cargo packages are not counted is $CARGO_HOME isn't set

### ISSUE THREAD

**Issue by laurentlbm** [Macchina-CLI/libmacchina#73]
`$CARGO_HOME` is used to override the location of the Cargo directory, but it is not mandatory. By default, Cargo uses in `$HOME/.cargo`.

**Comment by grtcdr** [comment]
Hmm, it might not be set as a global env variable but I'm pretty sure [cargo sets it](https://doc.rust-lang.org/cargo/reference/environment-variables.html) at runtime or something...

**Comment by grtcdr** [comment]
I do agree though, for a long time my cargo packages never appeared although they did appear on others' machines.

I'll use what you suggested instead.

**Comment by laurentlbm** [comment]
> Hmm, it might not be set as a global env variable but I'm pretty sure [cargo sets it](https://doc.rust-lang.org/cargo/reference/environment-variables.html) at runtime or something...

On my 2 machines (Arch and Fedora), it isn't set...

**Comment by grtcdr** [comment]
Fixed with https://github.com/Macchina-CLI/libmacchina/commit/1eba1b91153b07f734b898936651c49fd4eb4797

![2021-10-05T14:14:39,974818922+01:00](https://user-images.githubusercontent.com/35816711/136030126-5bdd152a-5aeb-4563-bcd3-ba4285fc344d.png)
