### ISSUE TITLE
[Feature] Count Homebrew packages on Linux

### ISSUE THREAD

**Issue by laurentlbm** [Macchina-CLI/libmacchina#74]
Homebrew's tagline is “The Missing Package Manager for macOS (or Linux)”. In this case, it's actually missing on Linux. 😁

**Comment by grtcdr** [comment]
I'll have to install Homebrew on Linux so I can check out where it stores its packages, or are you familiar with it?

**Comment by laurentlbm** [comment]
Some notes from my machine, I don't know if this can be generalized:

- I have two environmental variables that could be used: `$HOMEBREW_PREFIX` or `$HOMEBREW_CELLAR` (= `$HOMEBREW_PREFIX/Cellar`)
- There's a hidden file in the Cellar folder, `.keepme`, that should be ignored when counting

**Comment by grtcdr** [comment]
Where should we look if those environment variables aren't set?

**Comment by laurentlbm** [comment]
According to the [documentation](https://docs.brew.sh/Homebrew-on-Linux#install):

>  The installation script installs Homebrew to `/home/linuxbrew/.linuxbrew` using *sudo* if possible and in your home directory at `~/.linuxbrew` otherwise.

**Comment by laurentlbm** [comment]
That's equivalent to the variable `$HOMEBREW_PREFIX`.

**Comment by grtcdr** [comment]
Okay, great! Thanks for the help :)

**Comment by laurentlbm** [comment]
My pleasure. Good job btw, macchina has improved so much since its beginning!

**Comment by grtcdr** [comment]
Thank you so much :partying_face:

**Comment by grtcdr** [comment]
Does [this](https://github.com/Macchina-CLI/libmacchina/commit/b48af1b9d47de4bf49611e4db82036c757b2959a) look alright?

**Comment by laurentlbm** [comment]
Almost, it should count files in the `Cellar` sub-directory, so `$HOMEBREW_PREFIX/Cellar` or `$HOME/.linuxbrew/Cellar`.

**Comment by grtcdr** [comment]
Okay, so I finished it up, and did a quick simulation run:

![2021-10-05T15:44:13,535353559+01:00](https://user-images.githubusercontent.com/35816711/136046084-c2c511a6-6439-4abd-ae6a-a87e9d8d95a2.png)

**Comment by grtcdr** [comment]
v2.1.7 is out and it includes this change.
