### ISSUE TITLE
Brightness readout on NetBSD

### ISSUE THREAD

**Issue by 0323pin** [Macchina-CLI/libmacchina#89]
This is by no means a priority, it is simply surprising that it's failing with "Could not parse the obtained backlight value"
Reading the code in `libmacchina/src/netbsd/mod.rs`,

```
        fn backlight(&self) -> Result<usize, ReadoutError> {
        let output = Command::new("sysctl")
            .args(&["-n", "hw.acpi.acpiout0.brightness"])
            .output()
            .expect("ERROR: failed to fetch \"hw.acpi.acpiout0.brightness\" using \"sysctl\"");

        let backlight = String::from_utf8(output.stdout)
            .expect("ERROR: \"sysctl\" process stdout was not valid UTF-8");

        if backlight.is_empty() {
            return Err(ReadoutError::Other(String::from(
                "Could not obtain backlight value through sysctl, is ACPIVGA driver installed?",
            )));
        }

        if let Ok(val) = backlight.parse::<usize>() {
            return Ok(val);
        }

        Err(ReadoutError::Other(String::from(
            "Could not parse the obtained backlight value.",
        )))
```

If I run the commant on my shell, I can get a readout,

```
/home/pin()
2021-11-01 16:09 > sysctl -n hw.acpi.acpiout0.brightness
100
/home/pin()
2021-11-01 16:09 > 

```

Why is it failing to parse this output?

As said, no rush on fixing this. I know you have other priorities right now :)

**Comment by grtcdr** [comment]
It's failing right here:

```rust
if let Ok(val) = backlight.parse::<usize>() {
            return Ok(val);
}
```
I suspect a newline at the end of `100` that is making the parsing fail.

**Comment by 0323pin** [comment]
Thanks! Where it was failing was kind of obvious but, I didn't think about the new line.
`kern.ostype` is not failing. Isn't there a new line there also? Or, maybe not as the output is a String and not a value.

Can the new line be stripped off?

**Comment by grtcdr** [comment]
> Or, maybe not as the output is a String and not a value.

Yeah, any non-number can break `.parse()`

We can strip the newline and see if that fixes it, let me see what I can do. I unfortunately can't test this in a VM environment :(

**Comment by 0323pin** [comment]
Yeah, I know. A vm has its limitations.
Although, as is the readout is broken. We could go with your change and see if it works when I build it.

As said, the readout is broken right now, so we have nothing to loose, or?

**Comment by grtcdr** [comment]
macchina's now using libmacchina's latest version, fingers crossed :crossed_fingers: the issue is resolved.

**Comment by 0323pin** [comment]
Yeah, fingers crossed :)

**Comment by grtcdr** [comment]
*waiting eagerly*

**Comment by 0323pin** [comment]
> waiting eagerly

Yes, me too but, I don't have time until much later or, even tomorrow :(
I'll do my best, though

**Comment by grtcdr** [comment]
> > waiting eagerly
> 
> Yes, me too but, I don't have time until much later or, even tomorrow :( I'll do my best, though.

Oh, no worries, take your time :)

> Maybe, the Resolution readout is suffering from a similar issue?! But, one thing at the time.

Resolution hasn't been implemented yet. Remember when I mistakenly placed the backlight code in the resolution method?

**Comment by 0323pin** [comment]
> Resolution hasn't been implemented yet...

Yes, now I remember.

`libmacchina` v3.4.2 fixes the issue with brightness.
Thanks!

**Comment by grtcdr** [comment]
I figured it was that pesky newline :bug:

**Comment by 0323pin** [comment]
Once all these bugs are done, take a break. You deserve it :)

Next time Resolution and getting rid of `wmctrl` XD

**Comment by grtcdr** [comment]
> Next time Resolution and getting rid of wmctrl XD

The two things that haunt me everyday... hahaha

**Comment by 0323pin** [comment]
We all have our ghosts ;)

**Comment by grtcdr** [comment]
I guess so :ghost:
